# In this action we build the project
# which inserts the git branch name replacing __SRC_ROOT__ in dubplus.js
# then we commit this change to the target branch

name: Build

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - run: npm ci
      
      - name: build to insert branch name
        run: npm run build
      
      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dubplus.js
          git commit -m "[auto]: Update dubplus.js with branch name"
          git push
