# In this action we build the project
# which inserts the git branch name in dubplus.js
# then we commit this change to the target branch

name: Build

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Set git branch env var
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: echo "VITE_GIT_BRANCH=$BASE_REF" >> "$GITHUB_ENV"

      - run: npm audit --audit-level=critical

      - run: npm ci --ignore-scripts

      - name: build to insert branch name
        run: OUTPUT_DIR=. npm run ci:build

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dubplus.js dubplus.min.js dubplus.css
          git diff --staged --quiet || git commit -m "[auto]: Update dubplus.js with branch name"
          git push

      - name: Purge jsDelivr cache
        run: npm run purge-cache
