# In this action we build the project
# which inserts the git branch name in dubplus.js
# then we commit this change to the target branch

name: Build

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - run: echo "VITE_GIT_BRANCH=${{github.event.pull_request.base.ref}}" >> $GITHUB_ENV

      - run: npm ci

      - name: build to insert branch name
        run: npm run ci:build

      # we need to copy these files to root because bookmarklets expect them there
      - name: copy files to root
        run: |
          cp extension/dist/dubplus.js .
          cp extension/dist/dubplus.min.js .
          cp extension/dist/dubplus.css .

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dubplus.js
          git add dubplus.min.js
          git commit -m "[auto]: Update dubplus.js with branch name"
          git push

      - name: Purge jsDelivr cache
        run: npm run purge-cache
